In [1]:
import time
import numpy as np

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F
device = 'mps' if torch.backends.mps.is_built() else 'cpu'
device

'mps'

In [3]:
start_time = time.time()
zeros = torch.zeros(3, 3)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00018287


In [5]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

In [6]:
%%time
rand = torch_rand1 @ torch_rand2

CPU times: user 28.8 ms, sys: 38.5 ms, total: 67.3 ms
Wall time: 67.2 ms


In [7]:
%%time
rand = np_rand1 @ np_rand2

CPU times: user 129 ms, sys: 60 ms, total: 189 ms
Wall time: 187 ms


In [10]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [12]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5])
c = torch.cat((a, b), dim=0)
c

tensor([1, 2, 3, 4, 5])

In [15]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [20]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
input = torch.zeros(2, 3, 4)
out = torch.transpose(input, 1, 2)
out.shape

torch.Size([2, 4, 3])

In [27]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 3, 4])
tensor3 = torch.tensor([3, 4, 5])

stacked = torch.stack((tensor1, tensor2, tensor3))
stacked

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [29]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
out = linear(sample)
out

tensor([ 2.3449, -7.7960,  3.0991], grad_fn=<SqueezeBackward4>)

In [38]:
tensor1 = torch.tensor([1., 2., 3.])
softmax_out = F.softmax(tensor1, dim=0)
softmax_out

tensor([0.0900, 0.2447, 0.6652])

In [40]:
vocab_size = 20
embedding_size = 100
embedding = nn.Embedding(vocab_size, embedding_size)

input_indices = torch.LongTensor([1, 3, 2, 5])
embedding_out = embedding(input_indices)
embedding_out.shape

torch.Size([4, 100])

In [41]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2, 3], [2, 3, 4]])
c = torch.matmul(a, b)
c.shape

torch.Size([2, 3])